name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Lint with flake8
        run: |
          pip install flake8
          ./lint.sh
      - name: Test with pytest
        run: |
          pip install poetry
          poetry install
          poetry build
          ./test.sh
      - name: Upload code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash) -Z || echo 'Codecov failed to upload'
